[project]
name = "facts"
version = "0.1.0"
description = "Extracts, stores, and outputs Facts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["aw-client>=0.5.15", "pytest>=9.0.3"]

[project.scripts]
get_all = "facts.get_all:main"
megalog = "facts.megalog:main"
from_sqlite = "facts.from_sqlite:main"
from_aw = "facts.from_aw:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
