[project]
name = "megalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Dominic Mason", email = "dominicmason555@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["pytest>=9.0.3"]

[project.scripts]
megalog = "megalog:main"
sqlite_facts = "sqlite_facts:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = [
    "sqlite_facts",
]
